# Generated by Django 5.1.2 on 2026-01-06 14:34

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color_code',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_image',
            field=models.ImageField(upload_to='variants/'),
        ),
    ]
