# Generated by Django 5.1.2 on 2026-01-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_alter_category_options_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending ⏳'), ('Shipped', 'Shipped 🚚'), ('Delivered', 'Delivered ✅'), ('Canceled', 'Canceled ❌')], default='Pending', max_length=20, verbose_name='Order Status'),
        ),
    ]
