# Generated by Django 5.1.2 on 2026-01-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_stock_productvariant_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Total Stock Quantity'),
        ),
    ]
