# Generated by Django 5.1.2 on 2026-01-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False, verbose_name='New Arrival?'),
        ),
        migrations.AddField(
            model_name='product',
            name='new_arrival_updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
