# Generated by Django 5.1.2 on 2026-01-25 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_is_new_arrival_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='variant_image',
            field=models.ImageField(upload_to='variants/', verbose_name='Main Image for this Color'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='variants/extra/')),
                ('alt_text', models.CharField(blank=True, help_text='description', max_length=200, null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='store.productvariant')),
            ],
        ),
    ]
