# Generated by Django 5.1.2 on 2026-02-04 22:23

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_productvariant_variant_image_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[800, 1000], upload_to='variants/extra/'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[800, 1000], upload_to='variants/', verbose_name='Main Image for this Color'),
        ),
    ]
