# Generated by Django 5.1.2 on 2026-02-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='variants/extra/'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_image',
            field=models.ImageField(upload_to='variants/', verbose_name='Main Image for this Color'),
        ),
    ]
